### ISSUE TITLE
Travis build failing due to rogue comma

### ISSUE THREAD

**Issue by hughesj** [WASdev/standards.jsr352.tck#38]
The last commit means there's a JSON syntax error. [Travis build](https://travis-ci.org/WASdev/standards.jsr352.tck/builds/124506258) picked this up

**Comment by scottkurz** [comment]
@hughesj :  I'm guessing we may just be running out of threads during our "partition" tests which spawn a set of threads, based on [this](https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error) which is what I'm seeing, just a "Killed" in the middle of the Travis build log.

But you specifically mentioned a "rogue comma".  Did you have a reason for thinking this was something else?  

Otherwise, thinking we might just disable Travis rather than having to worry about limiting # of threads.

**Comment by scottkurz** [comment]
For now, pushed https://github.com/WASdev/standards.jsr352.tck/commit/196bf3c6e7ce21a291edeba87be4a323c646f7a2 to only run **test-compile** in travis.

**Comment by jvfullam** [comment]
Additionally, we decided to skip the tests in the Travis build of the RI in 099a5fd
